site_name: {{cookiecutter.project_name}}

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: default
    primary: black
    accent: blue
  icon:
    logo: fontawesome/solid/globe-africa

markdown_extensions:
  - footnotes

docs_dir: "../"
use_directory_urls: false

plugins:
  - search
  - bibtex:
      bib_file: "../../latex/library.bib"
      csl_file: "../../latex/copernicus.csl"
      cite_style: "pandoc"
